"""
Django settings for penden project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "fallback-secret-key-for-development-only")

DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'
# DEBUG = True

# In settings.py
ALLOWED_HOSTS = [
    'penden.store',
    'www.penden.store',
    'api.penden.store',
    'penden.online',  # ADD THIS
    'www.penden.online',  # ADD THIS
    'api.penden.online',  # ADD THIS
    'penden-backend.onrender.com',
    'localhost',
    '127.0.0.1',
    '.onrender.com',
]

CSRF_TRUSTED_ORIGINS = [
    "https://penden.store",
    "https://www.penden.store",
    "https://api.penden.store",
    "https://penden.online",  # ADD THIS
    "https://www.penden.online",  # ADD THIS
    "https://api.penden.online",  # ADD THIS
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://penden-backend.onrender.com",
    "https://penden-frontend.onrender.com",
]

CORS_ALLOWED_ORIGINS = [
    "https://penden.store",
    "https://www.penden.store",
    "https://api.penden.store",
    "https://penden.online",  # ADD THIS
    "https://www.penden.online",  # ADD THIS
    "https://api.penden.online",  # ADD THIS
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://penden-frontend.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local apps
    "accounts",
    "products",
    "footer",
    "orders",
    "about",
    "payment",
    "cart",
    "bot",

    # Third party
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",
    "django_redis",

    "health_check",
    "health_check.db",
    "health_check.cache",
    "health_check.storage",
    "drf_standardized_errors",
    "storages",
]

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "penden.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "penden.wsgi.application"

# Database - COMMENTED OUT DUE TO CONNECTION ERROR
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=not ('localhost' in os.environ.get('DATABASE_URL', '') or DEBUG),
    )
}

# Add this:
if 'localhost' in os.environ.get('DATABASE_URL', '') or DEBUG:
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'disable'
    }
else:
    DATABASES['default']['OPTIONS'] = {
        'sslmode': 'require'
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False

# Additional CORS settings
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Redis cache - simplified for production
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Session configuration - use database sessions to avoid cache issues
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 300

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# AWS Configuration
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')

# TEMPORARY: Force local storage until AWS permissions are fixed
USE_LOCAL_STORAGE = True  # Set to False after fixing AWS IAM permissions

# AWS Storage Configuration
if all([AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME,
        AWS_S3_REGION_NAME]) and not USE_LOCAL_STORAGE:
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

    # Use the safe storage class
    DEFAULT_FILE_STORAGE = 'penden.storage_backends.SafeS3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

else:
    # Fallback to local storage - THIS WILL PREVENT THE 500 ERROR
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password hashers
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Email Configuration - SIMPLIFIED to prevent 500 errors
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ADMINS = []  # Empty to prevent email error reporting

# Logging Configuration - CRITICAL FIX to prevent recursion errors
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Add specific logger for storages to catch S3 errors
        'storages': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'botocore': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# PayFast settings
PAYFAST_MERCHANT_ID = os.getenv("PAYFAST_MERCHANT_ID")
PAYFAST_MERCHANT_KEY = os.getenv("PAYFAST_MERCHANT_KEY")
PAYFAST_RETURN_URL = os.getenv("PAYFAST_RETURN_URL")
PAYFAST_CANCEL_URL = os.getenv("PAYFAST_CANCEL_URL")
PAYFAST_NOTIFY_URL = os.getenv("PAYFAST_NOTIFY_URL")

# Silenced system checks to prevent rate limiting warnings
SILENCED_SYSTEM_CHECKS = [
    'django_ratelimit.E003',
    'django_ratelimit.W001'
]